#!/usr/bin/env bash
#install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

#sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
#sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
