#!/usr/bin/env bash
#create a sustom 404 error page

# Update and install necessary packages
sudo apt-get update -y
sudo apt-get install -y nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \\t\terror_page 404 /custom_404.html;\n\t\terror_page 404 =404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

