#!/usr/bin/env bash
#double the number of servers: create a custom HTTP header
apt-get update
apt-get install -y nginx

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    server_name _;
    add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default

service nginx restart
