#!/usr/bin/env bash
# Install HAProxy version
apt-get update
apt-get install -y haproxy

printf %s "
frontend lb_front
        bind *:80
        mode http
        default_backend lb_back
backend lb_back
        balance roundrobin
        server 647530-web-01 18.234.145.228:80 check
        server 647530-web-02 54.157.183.178:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
