#!/usr/bin/env bash
#get nginx on our system
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)" #service nginx stop - for controlled ngiinx termination
