#!/usr/bin/env bash
# This script is displaying "bad luck" when the loop is on 4
# "good luck" when it's on 8 and "Best School" otherwise
i=1
while [ $i -le 10 ]
do
	if (( i == 4 )); then 
		echo "bad luck"
	elif (( i == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
