#!/usr/bin/env bash
#This script is diplaying contents of "ls"
for file in *;
do
    # Skip if it's a directory
    if [[ -f "$file" ]]; then
        # Remove everything up to and including the first dash
        formatted_name="${file#*-}"
        echo "$formatted_name"
    fi
done
