#!/usr/bin/env bash
#to file or not to file, that is the question
var="school"
if [ -e "$var" ];
then
	echo "$var file exists"
	if [ ! -s "$var" ];
	then
		echo "$var file is empty"
	else
		echo "$var file is not empty"
	fi
	if [ -f "$var" ];
	then
		echo "$var is a regular file"
	fi
else
	echo "$var file doesn't exist"
fi
