#!/usr/bin/env bash
#run nginx as nginx
sed -i "s/#user root/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
